config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Justin was here.
  # hey
  resources :categories

  resources :todos

  get "/signup" => "users#new"
  post "/users" => "users#create"

  get "/login" => "sessions#new"
  post "/sessions" => "sessions#create"
  get "/logout" => "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_todos
  has_many :todos, through: :category_todos
end

app/models/category_todo.rb
class CategoryTodo < ApplicationRecord
  belongs_to :category
  belongs_to :todo
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user 
  has_many :category_todos
  has_many :categories, through: :category_todos
end

app/models/user.rb
class User < ApplicationRecord
  has_many :todos
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authenticate_user
    redirect_to "/login", status: :see_other unless current_user
  end

  protect_from_forgery with: :exception, unless: -> { request.format.json? }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    render :index
  end

  def create
    @category = Category.create(
      name: params[:name],
    )
    render :show
  end

  def show
    @category = Category.find_by(id: params[:id])
    render :show
  end

  def update
    @category = Category.find_by(id: params[:id])
    @category.update(
      name: params[:name] || @category.name,
    )
    render :show
  end

  def destroy
    @category = Category.find_by(id: params[:id])
    @category.destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render template: "sessions/new"
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to "/"
    else
      redirect_to "/login"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/login"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
    render :index
  end

  def show
    @todo = Todo.find_by(id: params[:id])
    render :show
  end

  def new
    @todo = Todo.new
    render :new
  end

  def create
    @todo = Todo.create(
      user_id: current_user.id,
      title: params[:todo][:title],
      description: params[:todo][:description],
      deadline: params[:todo][:deadline],
      completed: params[:todo][:completed],
    )
    redirect_to "/todos"
  end

  def edit
    @todo = Todo.find_by(id: params[:id])
    render :edit
  end

  def update
    @todo = Todo.find_by(id: params[:id])
    @todo.update(
      user_id: current_user.id,
      title: params[:todo][:title],
      description: params[:todo][:description],
      deadline: params[:todo][:deadline],
      completed: params[:todo][:completed],
    )
    redirect_to "/todos"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render template: "users/new"
  end

  def create
    @user = User.new(
      name: params[:user][:name],
      email: params[:user][:email],
      password: params[:user][:password],
      password_confirmation: params[:user][:password_confirmation],
    )
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/"
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<h1>All categories</h1>
<% @categories.each do |category| %>
  <h2><%= category.name %></h2>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Todo-app</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
  <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="/login">New Todos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/signup">Signup</a>
            </li>
            <a class="nav-link" href="/login">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/logout">Logout</a>
            </li>
          </ul>
        </div>
      </div>
</nav>
   <div class = "container">
    <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/edit.html.erb
<h1>Edit Todo</h1>
<%= form_with model: @todo do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.label :deadline %>
    <%= form.text_field :deadline %>
  </div>
  <div>
    <%= form.label :completed %>
    <%= form.text_field :completed %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end%>

app/views/todos/index.html.erb
<h1>All Todos</h1>
<% @todos.each do |todo| %>
  <h2><%= todo.title %></h2>
<<<<<<< HEAD
  <p>Name: <%= todo.user.name %></p>
  <p>Description: <%= todo.description %></p>
  <p>Deadline: <%= todo.deadline %></p>
  <p>Done: <%= todo.completed %></p>
=======
  <p>user: <%= todo.user.name %></p>
  <p>description: <%= todo.description %></p>
  <p>deadline: <%= todo.deadline %></p>
  <p>completed?: <%= todo.completed %></p>
<%= link_to "More Info", todo %>
>>>>>>> d7ceadea04493cd290d92b5938bc4470cb84580e
<% end %>

app/views/todos/new.html.erb
<h1>New Todo</h1>
<%= form_with model: @todo do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.label :deadline %>
    <%= form.text_field :deadline %>
  </div>
  <div>
    <%= form.label :completed %>
    <%= form.text_field :completed %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end%>

app/views/todos/show.html.erb
<h1>Todo info</h1>
<h2><%= @todo.title %></h2>
<p>description: <%= @todo.description %></p>
<p>deadline: <%= @todo.deadline %></p>
<p>completed: <%= @todo.completed %></p>
<%= link_to "Edit todo", edit_todo_path(@todo) %>
<a href="/todos">Back to all todos</a>

app/views/users/new.html.erb
<h1>Signup</h1>
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name ,class: "form-control" %>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :email, class: "form-label" %>
    <%= form.email_field :email, class: "form-control" %>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :password, class: "form-label" %>
    <%= form.password_field :password, class: "form-control" %>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :password_confirmation, class: "form-label" %>
    <%= form.password_field :password_confirmation, class: "form-control" %>
    <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit "Signup", class: "btn btn-primary mt-4" %>
  </div>
<% end %>